package musgo

import (
	"os"
	"reflect"
	"testing"

	tdmg "github.com/ymz-ncnk/serialization/musgo/testdata/musgo"
)

// MusGo module tests code generated by the github.com/ymz-ncnk/musgen.
// Those tests are in 'musgen_..._test.go' files. If you want to test unsafe
// code, you should generate it first, see details in the testdata/gen/mus.go
// file.

// To get test coverage of the generated code:
// $ go test -coverpkg=./testdata/musgen -coverprofile=./testdata/musgen/coverage.out
// $ go tool cover -html=./testdata/musgen/coverage.out

func TestMusGo(t *testing.T) {
	musGo, err := New()
	if err != nil {
		t.Fatal(err)
	}
	conf := Conf{}
	conf.Path = "testdata/musgo"
	err = musGo.GenerateAs(reflect.TypeOf((*tdmg.IntAlias)(nil)).Elem(), conf)
	if err != nil {
		t.Fatal(err)
	}
	wantPath := conf.Path
	if _, err := os.Stat(wantPath); err != nil {
		t.Error("file was not generated")
	}
}
