// Code generated by musgen. DO NOT EDIT.

package musgen

import "github.com/ymz-ncnk/musgo/v2/errs"

// Marshal fills buf with the MUS encoding of v.
func (v BytePtrArrayPtrArrayAlias) Marshal(buf []byte) int {
	i := 0
	{
		for _, item := range v {
			if item == nil {
				buf[i] = 0
				i++
			} else {
				buf[i] = 1
				i++
				{
					for _, item := range *item {
						{
							buf[i] = byte(item)
							i++
						}
					}
				}
			}
		}
	}
	return i
}

// Unmarshal parses the MUS-encoded buf, and sets the result to *v.
func (v *BytePtrArrayPtrArrayAlias) Unmarshal(buf []byte) (int, error) {
	i := 0
	var err error
	{
		for j := 0; j < 2; j++ {
			(*v)[j] = new([2]uint8)
			if buf[i] == 0 {
				i++
				(*v)[j] = nil
			} else if buf[i] != 1 {
				i++
				return i, errs.ErrWrongByte
			} else {
				i++
				{
					for jj := 0; jj < 2; jj++ {
						{
							if i > len(buf)-1 {
								return i, errs.ErrSmallBuf
							}
							(*(*v)[j])[jj] = uint8(buf[i])
							i++
						}
						if err != nil {
							err = errs.NewArrayError(jj, err)
							break
						}
					}
				}
			}
			if err != nil {
				err = errs.NewArrayError(j, err)
				break
			}
		}
	}
	return i, err
}

// Size returns the size of the MUS-encoded v.
func (v BytePtrArrayPtrArrayAlias) Size() int {
	size := 0
	{
		for _, item := range v {
			size++
			if item != nil {
				{
					for _, item := range *item {
						{
							_ = item
							size++
						}
					}
				}
			}
		}
	}
	return size
}
