// Code generated by musgen. DO NOT EDIT.

package musgen

import "github.com/ymz-ncnk/musgo/errs"

// Marshal fills buf with the MUS encoding of v.
func (v BoolAlias) Marshal(buf []byte) int {
	i := 0
	{
		if v {
			buf[i] = 0x01
		} else {
			buf[i] = 0x00
		}
		i++
	}
	return i
}

// Unmarshal parses the MUS-encoded buf, and sets the result to *v.
func (v *BoolAlias) Unmarshal(buf []byte) (int, error) {
	i := 0
	var err error
	{
		if i > len(buf)-1 {
			return i, errs.ErrSmallBuf
		}
		if buf[i] == 0x01 {
			(*v) = true
			i++
		} else if buf[i] == 0x00 {
			(*v) = false
			i++
		} else {
			err = errs.ErrWrongByte
		}
	}
	return i, err
}

// Size returns the size of the MUS-encoded v.
func (v BoolAlias) Size() int {
	size := 0
	{
		_ = v
		size++
	}
	return size
}
