// Code generated by musgen. DO NOT EDIT.

package musgen

// Marshal fills buf with the MUS encoding of v.
func (v FieldlessStructType) Marshal(buf []byte) int {
	i := 0
	return i
}

// Unmarshal parses the MUS-encoded buf, and sets the result to *v.
func (v *FieldlessStructType) Unmarshal(buf []byte) (int, error) {
	i := 0
	var err error
	return i, err
}

// Size returns the size of the MUS-encoded v.
func (v FieldlessStructType) Size() int {
	size := 0
	return size
}
