// Code generated by musgen. DO NOT EDIT.

package musgen

import (
	"math"

	"github.com/ymz-ncnk/muserrs"
)

// Marshal fills buf with the MUS encoding of v.
func (v Float32RawAlias) Marshal(buf []byte) int {
	i := 0
	{
		uv := math.Float32bits(float32(v))
		{
			buf[i] = byte(uv)
			i++
			buf[i] = byte(uv >> 8)
			i++
			buf[i] = byte(uv >> 16)
			i++
			buf[i] = byte(uv >> 24)
			i++
		}
	}
	return i
}

// Unmarshal parses the MUS-encoded buf, and sets the result to *v.
func (v *Float32RawAlias) Unmarshal(buf []byte) (int, error) {
	i := 0
	var err error
	{
		var uv uint32
		{
			if len(buf) < 4 {
				return i, muserrs.ErrSmallBuf
			}
			uv = uint32(buf[i])
			i++
			uv |= uint32(buf[i]) << 8
			i++
			uv |= uint32(buf[i]) << 16
			i++
			uv |= uint32(buf[i]) << 24
			i++
		}
		(*v) = Float32RawAlias(math.Float32frombits(uv))
	}
	return i, err
}

// Size returns the size of the MUS-encoded v.
func (v Float32RawAlias) Size() int {
	size := 0
	{
		{
			_ = v
			size += 4
		}
	}
	return size
}
