// Code generated by musgen. DO NOT EDIT.

package musgen

import "github.com/ymz-ncnk/muserrs"

// Marshal fills buf with the MUS encoding of v.
func (v StructType) Marshal(buf []byte) int {
	i := 0
	{
		for v.Uint >= 0x80 {
			buf[i] = byte(v.Uint) | 0x80
			v.Uint >>= 7
			i++
		}
		buf[i] = byte(v.Uint)
		i++
	}
	{
		for v.Uint16 >= 0x80 {
			buf[i] = byte(v.Uint16) | 0x80
			v.Uint16 >>= 7
			i++
		}
		buf[i] = byte(v.Uint16)
		i++
	}
	{
		for v.Uint32 >= 0x80 {
			buf[i] = byte(v.Uint32) | 0x80
			v.Uint32 >>= 7
			i++
		}
		buf[i] = byte(v.Uint32)
		i++
	}
	{
		for v.Uint64 >= 0x80 {
			buf[i] = byte(v.Uint64) | 0x80
			v.Uint64 >>= 7
			i++
		}
		buf[i] = byte(v.Uint64)
		i++
	}
	if v.UintPtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			tmp := (*v.UintPtr)
			for tmp >= 0x80 {
				buf[i] = byte(tmp) | 0x80
				tmp >>= 7
				i++
			}
			buf[i] = byte(tmp)
			i++
		}
	}
	if v.UintPtrPtrPtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			tmp := (***v.UintPtrPtrPtr)
			for tmp >= 0x80 {
				buf[i] = byte(tmp) | 0x80
				tmp >>= 7
				i++
			}
			buf[i] = byte(tmp)
			i++
		}
	}
	{
		uv := uint64(v.Int)
		if v.Int < 0 {
			uv = ^(uv << 1)
		} else {
			uv = uv << 1
		}
		{
			for uv >= 0x80 {
				buf[i] = byte(uv) | 0x80
				uv >>= 7
				i++
			}
			buf[i] = byte(uv)
			i++
		}
	}
	{
		buf[i] = byte(v.Int8)
		i++
	}
	{
		uv := uint16(v.Int16)
		if v.Int16 < 0 {
			uv = ^(uv << 1)
		} else {
			uv = uv << 1
		}
		{
			for uv >= 0x80 {
				buf[i] = byte(uv) | 0x80
				uv >>= 7
				i++
			}
			buf[i] = byte(uv)
			i++
		}
	}
	{
		uv := uint32(v.Int32)
		if v.Int32 < 0 {
			uv = ^(uv << 1)
		} else {
			uv = uv << 1
		}
		{
			for uv >= 0x80 {
				buf[i] = byte(uv) | 0x80
				uv >>= 7
				i++
			}
			buf[i] = byte(uv)
			i++
		}
	}
	{
		uv := uint64(v.Int64)
		if v.Int64 < 0 {
			uv = ^(uv << 1)
		} else {
			uv = uv << 1
		}
		{
			for uv >= 0x80 {
				buf[i] = byte(uv) | 0x80
				uv >>= 7
				i++
			}
			buf[i] = byte(uv)
			i++
		}
	}
	if v.IntPtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			uv := uint64((*v.IntPtr))
			if (*v.IntPtr) < 0 {
				uv = ^(uv << 1)
			} else {
				uv = uv << 1
			}
			{
				for uv >= 0x80 {
					buf[i] = byte(uv) | 0x80
					uv >>= 7
					i++
				}
				buf[i] = byte(uv)
				i++
			}
		}
	}
	if v.IntPtrPtrPtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			uv := uint64((***v.IntPtrPtrPtr))
			if (***v.IntPtrPtrPtr) < 0 {
				uv = ^(uv << 1)
			} else {
				uv = uv << 1
			}
			{
				for uv >= 0x80 {
					buf[i] = byte(uv) | 0x80
					uv >>= 7
					i++
				}
				buf[i] = byte(uv)
				i++
			}
		}
	}
	if v.IntAliasPtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			si := (*v.IntAliasPtr).Marshal(buf[i:])
			i += si
		}
	}
	{
		length := len(v.String)
		{
			uv := uint64(length)
			if length < 0 {
				uv = ^(uv << 1)
			} else {
				uv = uv << 1
			}
			{
				for uv >= 0x80 {
					buf[i] = byte(uv) | 0x80
					uv >>= 7
					i++
				}
				buf[i] = byte(uv)
				i++
			}
		}
		if len(buf[i:]) < length {
			panic(muserrs.ErrSmallBuf)
		}
		i += copy(buf[i:], v.String)
	}
	if v.StringPtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			length := len((*v.StringPtr))
			{
				uv := uint64(length)
				if length < 0 {
					uv = ^(uv << 1)
				} else {
					uv = uv << 1
				}
				{
					for uv >= 0x80 {
						buf[i] = byte(uv) | 0x80
						uv >>= 7
						i++
					}
					buf[i] = byte(uv)
					i++
				}
			}
			if len(buf[i:]) < length {
				panic(muserrs.ErrSmallBuf)
			}
			i += copy(buf[i:], (*v.StringPtr))
		}
	}
	if v.StringPtrPtrPtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			length := len((***v.StringPtrPtrPtr))
			{
				uv := uint64(length)
				if length < 0 {
					uv = ^(uv << 1)
				} else {
					uv = uv << 1
				}
				{
					for uv >= 0x80 {
						buf[i] = byte(uv) | 0x80
						uv >>= 7
						i++
					}
					buf[i] = byte(uv)
					i++
				}
			}
			if len(buf[i:]) < length {
				panic(muserrs.ErrSmallBuf)
			}
			i += copy(buf[i:], (***v.StringPtrPtrPtr))
		}
	}
	{
		buf[i] = byte(v.Byte)
		i++
	}
	if v.BytePtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			buf[i] = byte((*v.BytePtr))
			i++
		}
	}
	if v.BytePtrPtrPtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			buf[i] = byte((***v.BytePtrPtrPtr))
			i++
		}
	}
	{
		if v.Bool {
			buf[i] = 0x01
		} else {
			buf[i] = 0x00
		}
		i++
	}
	if v.BoolPtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			if *v.BoolPtr {
				buf[i] = 0x01
			} else {
				buf[i] = 0x00
			}
			i++
		}
	}
	if v.BoolPtrPtrPtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			if ***v.BoolPtrPtrPtr {
				buf[i] = 0x01
			} else {
				buf[i] = 0x00
			}
			i++
		}
	}
	{
		length := len(v.Slice)
		{
			uv := uint64(length)
			if length < 0 {
				uv = ^(uv << 1)
			} else {
				uv = uv << 1
			}
			{
				for uv >= 0x80 {
					buf[i] = byte(uv) | 0x80
					uv >>= 7
					i++
				}
				buf[i] = byte(uv)
				i++
			}
		}
		for _, el := range v.Slice {
			{
				for el >= 0x80 {
					buf[i] = byte(el) | 0x80
					el >>= 7
					i++
				}
				buf[i] = byte(el)
				i++
			}
		}
	}
	if v.SlicePtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			length := len((*v.SlicePtr))
			{
				uv := uint64(length)
				if length < 0 {
					uv = ^(uv << 1)
				} else {
					uv = uv << 1
				}
				{
					for uv >= 0x80 {
						buf[i] = byte(uv) | 0x80
						uv >>= 7
						i++
					}
					buf[i] = byte(uv)
					i++
				}
			}
			for _, el := range *v.SlicePtr {
				{
					for el >= 0x80 {
						buf[i] = byte(el) | 0x80
						el >>= 7
						i++
					}
					buf[i] = byte(el)
					i++
				}
			}
		}
	}
	if v.SlicePtrPtrPtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			length := len((***v.SlicePtrPtrPtr))
			{
				uv := uint64(length)
				if length < 0 {
					uv = ^(uv << 1)
				} else {
					uv = uv << 1
				}
				{
					for uv >= 0x80 {
						buf[i] = byte(uv) | 0x80
						uv >>= 7
						i++
					}
					buf[i] = byte(uv)
					i++
				}
			}
			for _, el := range ***v.SlicePtrPtrPtr {
				{
					for el >= 0x80 {
						buf[i] = byte(el) | 0x80
						el >>= 7
						i++
					}
					buf[i] = byte(el)
					i++
				}
			}
		}
	}
	{
		for _, item := range v.Array {
			{
				uv := uint64(item)
				if item < 0 {
					uv = ^(uv << 1)
				} else {
					uv = uv << 1
				}
				{
					for uv >= 0x80 {
						buf[i] = byte(uv) | 0x80
						uv >>= 7
						i++
					}
					buf[i] = byte(uv)
					i++
				}
			}
		}
	}
	if v.ArrayPtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			for _, item := range *v.ArrayPtr {
				{
					uv := uint32(item)
					if item < 0 {
						uv = ^(uv << 1)
					} else {
						uv = uv << 1
					}
					{
						for uv >= 0x80 {
							buf[i] = byte(uv) | 0x80
							uv >>= 7
							i++
						}
						buf[i] = byte(uv)
						i++
					}
				}
			}
		}
	}
	if v.ArrayPtrPtrPtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			for _, item := range ***v.ArrayPtrPtrPtr {
				{
					uv := uint32(item)
					if item < 0 {
						uv = ^(uv << 1)
					} else {
						uv = uv << 1
					}
					{
						for uv >= 0x80 {
							buf[i] = byte(uv) | 0x80
							uv >>= 7
							i++
						}
						buf[i] = byte(uv)
						i++
					}
				}
			}
		}
	}
	{
		length := len(v.Map)
		{
			uv := uint64(length)
			if length < 0 {
				uv = ^(uv << 1)
			} else {
				uv = uv << 1
			}
			{
				for uv >= 0x80 {
					buf[i] = byte(uv) | 0x80
					uv >>= 7
					i++
				}
				buf[i] = byte(uv)
				i++
			}
		}
		for ke, vl := range v.Map {
			{
				length := len(ke)
				{
					uv := uint64(length)
					if length < 0 {
						uv = ^(uv << 1)
					} else {
						uv = uv << 1
					}
					{
						for uv >= 0x80 {
							buf[i] = byte(uv) | 0x80
							uv >>= 7
							i++
						}
						buf[i] = byte(uv)
						i++
					}
				}
				if len(buf[i:]) < length {
					panic(muserrs.ErrSmallBuf)
				}
				i += copy(buf[i:], ke)
			}
			{
				uv := uint64(vl)
				if vl < 0 {
					uv = ^(uv << 1)
				} else {
					uv = uv << 1
				}
				{
					for uv >= 0x80 {
						buf[i] = byte(uv) | 0x80
						uv >>= 7
						i++
					}
					buf[i] = byte(uv)
					i++
				}
			}
		}
	}
	if v.MapPtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			length := len((*v.MapPtr))
			{
				uv := uint64(length)
				if length < 0 {
					uv = ^(uv << 1)
				} else {
					uv = uv << 1
				}
				{
					for uv >= 0x80 {
						buf[i] = byte(uv) | 0x80
						uv >>= 7
						i++
					}
					buf[i] = byte(uv)
					i++
				}
			}
			for ke, vl := range *v.MapPtr {
				{
					length := len(ke)
					{
						uv := uint64(length)
						if length < 0 {
							uv = ^(uv << 1)
						} else {
							uv = uv << 1
						}
						{
							for uv >= 0x80 {
								buf[i] = byte(uv) | 0x80
								uv >>= 7
								i++
							}
							buf[i] = byte(uv)
							i++
						}
					}
					if len(buf[i:]) < length {
						panic(muserrs.ErrSmallBuf)
					}
					i += copy(buf[i:], ke)
				}
				{
					uv := uint64(vl)
					if vl < 0 {
						uv = ^(uv << 1)
					} else {
						uv = uv << 1
					}
					{
						for uv >= 0x80 {
							buf[i] = byte(uv) | 0x80
							uv >>= 7
							i++
						}
						buf[i] = byte(uv)
						i++
					}
				}
			}
		}
	}
	if v.MapPtrPtrPtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			length := len((***v.MapPtrPtrPtr))
			{
				uv := uint64(length)
				if length < 0 {
					uv = ^(uv << 1)
				} else {
					uv = uv << 1
				}
				{
					for uv >= 0x80 {
						buf[i] = byte(uv) | 0x80
						uv >>= 7
						i++
					}
					buf[i] = byte(uv)
					i++
				}
			}
			for ke, vl := range ***v.MapPtrPtrPtr {
				{
					length := len(ke)
					{
						uv := uint64(length)
						if length < 0 {
							uv = ^(uv << 1)
						} else {
							uv = uv << 1
						}
						{
							for uv >= 0x80 {
								buf[i] = byte(uv) | 0x80
								uv >>= 7
								i++
							}
							buf[i] = byte(uv)
							i++
						}
					}
					if len(buf[i:]) < length {
						panic(muserrs.ErrSmallBuf)
					}
					i += copy(buf[i:], ke)
				}
				{
					uv := uint64(vl)
					if vl < 0 {
						uv = ^(uv << 1)
					} else {
						uv = uv << 1
					}
					{
						for uv >= 0x80 {
							buf[i] = byte(uv) | 0x80
							uv >>= 7
							i++
						}
						buf[i] = byte(uv)
						i++
					}
				}
			}
		}
	}
	{
		si := v.Struct.Marshal(buf[i:])
		i += si
	}
	if v.StructPtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			si := (*v.StructPtr).Marshal(buf[i:])
			i += si
		}
	}
	if v.StructPtrPtrPtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			si := (***v.StructPtrPtrPtr).Marshal(buf[i:])
			i += si
		}
	}
	{
		for _, item := range v.Tricky {
			{
				length := len(item)
				{
					uv := uint64(length)
					if length < 0 {
						uv = ^(uv << 1)
					} else {
						uv = uv << 1
					}
					{
						for uv >= 0x80 {
							buf[i] = byte(uv) | 0x80
							uv >>= 7
							i++
						}
						buf[i] = byte(uv)
						i++
					}
				}
				for ke, vl := range item {
					{
						for _, item := range ke {
							{
								si := item.Marshal(buf[i:])
								i += si
							}
						}
					}
					{
						length := len(vl)
						{
							uv := uint64(length)
							if length < 0 {
								uv = ^(uv << 1)
							} else {
								uv = uv << 1
							}
							{
								for uv >= 0x80 {
									buf[i] = byte(uv) | 0x80
									uv >>= 7
									i++
								}
								buf[i] = byte(uv)
								i++
							}
						}
						for ke, vl := range vl {
							{
								si := ke.Marshal(buf[i:])
								i += si
							}
							{
								for _, item := range vl {
									{
										length := len(item)
										{
											uv := uint64(length)
											if length < 0 {
												uv = ^(uv << 1)
											} else {
												uv = uv << 1
											}
											{
												for uv >= 0x80 {
													buf[i] = byte(uv) | 0x80
													uv >>= 7
													i++
												}
												buf[i] = byte(uv)
												i++
											}
										}
										if len(buf[i:]) < length {
											panic(muserrs.ErrSmallBuf)
										}
										i += copy(buf[i:], item)
									}
								}
							}
						}
					}
				}
			}
		}
	}
	return i
}

// Unmarshal parses the MUS-encoded buf, and sets the result to *v.
func (v *StructType) Unmarshal(buf []byte) (int, error) {
	i := 0
	var err error
	{
		if i > len(buf)-1 {
			return i, muserrs.ErrSmallBuf
		}
		shift := 0
		done := false
		for l, b := range buf[i:] {
			if l == 9 && b > 1 {
				return i, muserrs.ErrOverflow
			}
			if b < 0x80 {
				v.Uint = v.Uint | uint(b)<<shift
				done = true
				i += l + 1
				break
			}
			v.Uint = v.Uint | uint(b&0x7F)<<shift
			shift += 7
		}
		if !done {
			return i, muserrs.ErrSmallBuf
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("Uint", err)
	}
	{
		if i > len(buf)-1 {
			return i, muserrs.ErrSmallBuf
		}
		shift := 0
		done := false
		for l, b := range buf[i:] {
			if l == 2 && b > 3 {
				return i, muserrs.ErrOverflow
			}
			if b < 0x80 {
				v.Uint16 = v.Uint16 | uint16(b)<<shift
				done = true
				i += l + 1
				break
			}
			v.Uint16 = v.Uint16 | uint16(b&0x7F)<<shift
			shift += 7
		}
		if !done {
			return i, muserrs.ErrSmallBuf
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("Uint16", err)
	}
	{
		if i > len(buf)-1 {
			return i, muserrs.ErrSmallBuf
		}
		shift := 0
		done := false
		for l, b := range buf[i:] {
			if l == 4 && b > 15 {
				return i, muserrs.ErrOverflow
			}
			if b < 0x80 {
				v.Uint32 = v.Uint32 | uint32(b)<<shift
				done = true
				i += l + 1
				break
			}
			v.Uint32 = v.Uint32 | uint32(b&0x7F)<<shift
			shift += 7
		}
		if !done {
			return i, muserrs.ErrSmallBuf
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("Uint32", err)
	}
	{
		if i > len(buf)-1 {
			return i, muserrs.ErrSmallBuf
		}
		shift := 0
		done := false
		for l, b := range buf[i:] {
			if l == 9 && b > 1 {
				return i, muserrs.ErrOverflow
			}
			if b < 0x80 {
				v.Uint64 = v.Uint64 | uint64(b)<<shift
				done = true
				i += l + 1
				break
			}
			v.Uint64 = v.Uint64 | uint64(b&0x7F)<<shift
			shift += 7
		}
		if !done {
			return i, muserrs.ErrSmallBuf
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("Uint64", err)
	}
	v.UintPtr = new(uint)
	if buf[i] == 0 {
		i++
		v.UintPtr = nil
	} else if buf[i] != 1 {
		i++
		return i, muserrs.ErrWrongByte
	} else {
		i++
		{
			if i > len(buf)-1 {
				return i, muserrs.ErrSmallBuf
			}
			shift := 0
			done := false
			for l, b := range buf[i:] {
				if l == 9 && b > 1 {
					return i, muserrs.ErrOverflow
				}
				if b < 0x80 {
					(*v.UintPtr) = (*v.UintPtr) | uint(b)<<shift
					done = true
					i += l + 1
					break
				}
				(*v.UintPtr) = (*v.UintPtr) | uint(b&0x7F)<<shift
				shift += 7
			}
			if !done {
				return i, muserrs.ErrSmallBuf
			}
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("UintPtr", err)
	}
	{
		tmp0 := new(uint)
		tmp1 := &tmp0
		v.UintPtrPtrPtr = &tmp1
	}
	if buf[i] == 0 {
		i++
		v.UintPtrPtrPtr = nil
	} else if buf[i] != 1 {
		i++
		return i, muserrs.ErrWrongByte
	} else {
		i++
		{
			if i > len(buf)-1 {
				return i, muserrs.ErrSmallBuf
			}
			shift := 0
			done := false
			for l, b := range buf[i:] {
				if l == 9 && b > 1 {
					return i, muserrs.ErrOverflow
				}
				if b < 0x80 {
					(***v.UintPtrPtrPtr) = (***v.UintPtrPtrPtr) | uint(b)<<shift
					done = true
					i += l + 1
					break
				}
				(***v.UintPtrPtrPtr) = (***v.UintPtrPtrPtr) | uint(b&0x7F)<<shift
				shift += 7
			}
			if !done {
				return i, muserrs.ErrSmallBuf
			}
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("UintPtrPtrPtr", err)
	}
	{
		var uv uint64
		{
			if i > len(buf)-1 {
				return i, muserrs.ErrSmallBuf
			}
			shift := 0
			done := false
			for l, b := range buf[i:] {
				if l == 9 && b > 1 {
					return i, muserrs.ErrOverflow
				}
				if b < 0x80 {
					uv = uv | uint64(b)<<shift
					done = true
					i += l + 1
					break
				}
				uv = uv | uint64(b&0x7F)<<shift
				shift += 7
			}
			if !done {
				return i, muserrs.ErrSmallBuf
			}
		}
		if uv&1 == 1 {
			uv = ^(uv >> 1)
		} else {
			uv = uv >> 1
		}
		v.Int = int(uv)
	}
	if err != nil {
		return i, muserrs.NewFieldError("Int", err)
	}
	{
		if i > len(buf)-1 {
			return i, muserrs.ErrSmallBuf
		}
		v.Int8 = int8(buf[i])
		i++
	}
	if err != nil {
		return i, muserrs.NewFieldError("Int8", err)
	}
	{
		var uv uint16
		{
			if i > len(buf)-1 {
				return i, muserrs.ErrSmallBuf
			}
			shift := 0
			done := false
			for l, b := range buf[i:] {
				if l == 2 && b > 3 {
					return i, muserrs.ErrOverflow
				}
				if b < 0x80 {
					uv = uv | uint16(b)<<shift
					done = true
					i += l + 1
					break
				}
				uv = uv | uint16(b&0x7F)<<shift
				shift += 7
			}
			if !done {
				return i, muserrs.ErrSmallBuf
			}
		}
		if uv&1 == 1 {
			uv = ^(uv >> 1)
		} else {
			uv = uv >> 1
		}
		v.Int16 = int16(uv)
	}
	if err != nil {
		return i, muserrs.NewFieldError("Int16", err)
	}
	{
		var uv uint32
		{
			if i > len(buf)-1 {
				return i, muserrs.ErrSmallBuf
			}
			shift := 0
			done := false
			for l, b := range buf[i:] {
				if l == 4 && b > 15 {
					return i, muserrs.ErrOverflow
				}
				if b < 0x80 {
					uv = uv | uint32(b)<<shift
					done = true
					i += l + 1
					break
				}
				uv = uv | uint32(b&0x7F)<<shift
				shift += 7
			}
			if !done {
				return i, muserrs.ErrSmallBuf
			}
		}
		if uv&1 == 1 {
			uv = ^(uv >> 1)
		} else {
			uv = uv >> 1
		}
		v.Int32 = int32(uv)
	}
	if err != nil {
		return i, muserrs.NewFieldError("Int32", err)
	}
	{
		var uv uint64
		{
			if i > len(buf)-1 {
				return i, muserrs.ErrSmallBuf
			}
			shift := 0
			done := false
			for l, b := range buf[i:] {
				if l == 9 && b > 1 {
					return i, muserrs.ErrOverflow
				}
				if b < 0x80 {
					uv = uv | uint64(b)<<shift
					done = true
					i += l + 1
					break
				}
				uv = uv | uint64(b&0x7F)<<shift
				shift += 7
			}
			if !done {
				return i, muserrs.ErrSmallBuf
			}
		}
		if uv&1 == 1 {
			uv = ^(uv >> 1)
		} else {
			uv = uv >> 1
		}
		v.Int64 = int64(uv)
	}
	if err != nil {
		return i, muserrs.NewFieldError("Int64", err)
	}
	v.IntPtr = new(int)
	if buf[i] == 0 {
		i++
		v.IntPtr = nil
	} else if buf[i] != 1 {
		i++
		return i, muserrs.ErrWrongByte
	} else {
		i++
		{
			var uv uint64
			{
				if i > len(buf)-1 {
					return i, muserrs.ErrSmallBuf
				}
				shift := 0
				done := false
				for l, b := range buf[i:] {
					if l == 9 && b > 1 {
						return i, muserrs.ErrOverflow
					}
					if b < 0x80 {
						uv = uv | uint64(b)<<shift
						done = true
						i += l + 1
						break
					}
					uv = uv | uint64(b&0x7F)<<shift
					shift += 7
				}
				if !done {
					return i, muserrs.ErrSmallBuf
				}
			}
			if uv&1 == 1 {
				uv = ^(uv >> 1)
			} else {
				uv = uv >> 1
			}
			(*v.IntPtr) = int(uv)
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("IntPtr", err)
	}
	{
		tmp0 := new(int)
		tmp1 := &tmp0
		v.IntPtrPtrPtr = &tmp1
	}
	if buf[i] == 0 {
		i++
		v.IntPtrPtrPtr = nil
	} else if buf[i] != 1 {
		i++
		return i, muserrs.ErrWrongByte
	} else {
		i++
		{
			var uv uint64
			{
				if i > len(buf)-1 {
					return i, muserrs.ErrSmallBuf
				}
				shift := 0
				done := false
				for l, b := range buf[i:] {
					if l == 9 && b > 1 {
						return i, muserrs.ErrOverflow
					}
					if b < 0x80 {
						uv = uv | uint64(b)<<shift
						done = true
						i += l + 1
						break
					}
					uv = uv | uint64(b&0x7F)<<shift
					shift += 7
				}
				if !done {
					return i, muserrs.ErrSmallBuf
				}
			}
			if uv&1 == 1 {
				uv = ^(uv >> 1)
			} else {
				uv = uv >> 1
			}
			(***v.IntPtrPtrPtr) = int(uv)
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("IntPtrPtrPtr", err)
	}
	v.IntAliasPtr = new(IntAlias)
	if buf[i] == 0 {
		i++
		v.IntAliasPtr = nil
	} else if buf[i] != 1 {
		i++
		return i, muserrs.ErrWrongByte
	} else {
		i++
		{
			var sv IntAlias
			si := 0
			si, err = sv.Unmarshal(buf[i:])
			if err == nil {
				(*v.IntAliasPtr) = sv
				i += si
			}
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("IntAliasPtr", err)
	}
	{
		var length int
		{
			var uv uint64
			{
				if i > len(buf)-1 {
					return i, muserrs.ErrSmallBuf
				}
				shift := 0
				done := false
				for l, b := range buf[i:] {
					if l == 9 && b > 1 {
						return i, muserrs.ErrOverflow
					}
					if b < 0x80 {
						uv = uv | uint64(b)<<shift
						done = true
						i += l + 1
						break
					}
					uv = uv | uint64(b&0x7F)<<shift
					shift += 7
				}
				if !done {
					return i, muserrs.ErrSmallBuf
				}
			}
			if uv&1 == 1 {
				uv = ^(uv >> 1)
			} else {
				uv = uv >> 1
			}
			length = int(uv)
		}
		if length < 0 {
			return i, muserrs.ErrNegativeLength
		}
		if len(buf) < i+length {
			return i, muserrs.ErrSmallBuf
		}
		v.String = string(buf[i : i+length])
		i += length
	}
	if err != nil {
		return i, muserrs.NewFieldError("String", err)
	}
	v.StringPtr = new(string)
	if buf[i] == 0 {
		i++
		v.StringPtr = nil
	} else if buf[i] != 1 {
		i++
		return i, muserrs.ErrWrongByte
	} else {
		i++
		{
			var length int
			{
				var uv uint64
				{
					if i > len(buf)-1 {
						return i, muserrs.ErrSmallBuf
					}
					shift := 0
					done := false
					for l, b := range buf[i:] {
						if l == 9 && b > 1 {
							return i, muserrs.ErrOverflow
						}
						if b < 0x80 {
							uv = uv | uint64(b)<<shift
							done = true
							i += l + 1
							break
						}
						uv = uv | uint64(b&0x7F)<<shift
						shift += 7
					}
					if !done {
						return i, muserrs.ErrSmallBuf
					}
				}
				if uv&1 == 1 {
					uv = ^(uv >> 1)
				} else {
					uv = uv >> 1
				}
				length = int(uv)
			}
			if length < 0 {
				return i, muserrs.ErrNegativeLength
			}
			if len(buf) < i+length {
				return i, muserrs.ErrSmallBuf
			}
			(*v.StringPtr) = string(buf[i : i+length])
			i += length
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("StringPtr", err)
	}
	{
		tmp0 := new(string)
		tmp1 := &tmp0
		v.StringPtrPtrPtr = &tmp1
	}
	if buf[i] == 0 {
		i++
		v.StringPtrPtrPtr = nil
	} else if buf[i] != 1 {
		i++
		return i, muserrs.ErrWrongByte
	} else {
		i++
		{
			var length int
			{
				var uv uint64
				{
					if i > len(buf)-1 {
						return i, muserrs.ErrSmallBuf
					}
					shift := 0
					done := false
					for l, b := range buf[i:] {
						if l == 9 && b > 1 {
							return i, muserrs.ErrOverflow
						}
						if b < 0x80 {
							uv = uv | uint64(b)<<shift
							done = true
							i += l + 1
							break
						}
						uv = uv | uint64(b&0x7F)<<shift
						shift += 7
					}
					if !done {
						return i, muserrs.ErrSmallBuf
					}
				}
				if uv&1 == 1 {
					uv = ^(uv >> 1)
				} else {
					uv = uv >> 1
				}
				length = int(uv)
			}
			if length < 0 {
				return i, muserrs.ErrNegativeLength
			}
			if len(buf) < i+length {
				return i, muserrs.ErrSmallBuf
			}
			(***v.StringPtrPtrPtr) = string(buf[i : i+length])
			i += length
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("StringPtrPtrPtr", err)
	}
	{
		if i > len(buf)-1 {
			return i, muserrs.ErrSmallBuf
		}
		v.Byte = uint8(buf[i])
		i++
	}
	if err != nil {
		return i, muserrs.NewFieldError("Byte", err)
	}
	v.BytePtr = new(uint8)
	if buf[i] == 0 {
		i++
		v.BytePtr = nil
	} else if buf[i] != 1 {
		i++
		return i, muserrs.ErrWrongByte
	} else {
		i++
		{
			if i > len(buf)-1 {
				return i, muserrs.ErrSmallBuf
			}
			(*v.BytePtr) = uint8(buf[i])
			i++
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("BytePtr", err)
	}
	{
		tmp0 := new(uint8)
		tmp1 := &tmp0
		v.BytePtrPtrPtr = &tmp1
	}
	if buf[i] == 0 {
		i++
		v.BytePtrPtrPtr = nil
	} else if buf[i] != 1 {
		i++
		return i, muserrs.ErrWrongByte
	} else {
		i++
		{
			if i > len(buf)-1 {
				return i, muserrs.ErrSmallBuf
			}
			(***v.BytePtrPtrPtr) = uint8(buf[i])
			i++
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("BytePtrPtrPtr", err)
	}
	{
		if i > len(buf)-1 {
			return i, muserrs.ErrSmallBuf
		}
		if buf[i] == 0x01 {
			v.Bool = true
			i++
		} else if buf[i] == 0x00 {
			v.Bool = false
			i++
		} else {
			err = muserrs.ErrWrongByte
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("Bool", err)
	}
	v.BoolPtr = new(bool)
	if buf[i] == 0 {
		i++
		v.BoolPtr = nil
	} else if buf[i] != 1 {
		i++
		return i, muserrs.ErrWrongByte
	} else {
		i++
		{
			if i > len(buf)-1 {
				return i, muserrs.ErrSmallBuf
			}
			if buf[i] == 0x01 {
				(*v.BoolPtr) = true
				i++
			} else if buf[i] == 0x00 {
				(*v.BoolPtr) = false
				i++
			} else {
				err = muserrs.ErrWrongByte
			}
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("BoolPtr", err)
	}
	{
		tmp0 := new(bool)
		tmp1 := &tmp0
		v.BoolPtrPtrPtr = &tmp1
	}
	if buf[i] == 0 {
		i++
		v.BoolPtrPtrPtr = nil
	} else if buf[i] != 1 {
		i++
		return i, muserrs.ErrWrongByte
	} else {
		i++
		{
			if i > len(buf)-1 {
				return i, muserrs.ErrSmallBuf
			}
			if buf[i] == 0x01 {
				(***v.BoolPtrPtrPtr) = true
				i++
			} else if buf[i] == 0x00 {
				(***v.BoolPtrPtrPtr) = false
				i++
			} else {
				err = muserrs.ErrWrongByte
			}
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("BoolPtrPtrPtr", err)
	}
	{
		var length int
		{
			var uv uint64
			{
				if i > len(buf)-1 {
					return i, muserrs.ErrSmallBuf
				}
				shift := 0
				done := false
				for l, b := range buf[i:] {
					if l == 9 && b > 1 {
						return i, muserrs.ErrOverflow
					}
					if b < 0x80 {
						uv = uv | uint64(b)<<shift
						done = true
						i += l + 1
						break
					}
					uv = uv | uint64(b&0x7F)<<shift
					shift += 7
				}
				if !done {
					return i, muserrs.ErrSmallBuf
				}
			}
			if uv&1 == 1 {
				uv = ^(uv >> 1)
			} else {
				uv = uv >> 1
			}
			length = int(uv)
		}
		if length < 0 {
			return i, muserrs.ErrNegativeLength
		}
		v.Slice = make([]uint, length)
		for j := 0; j < length; j++ {
			{
				if i > len(buf)-1 {
					return i, muserrs.ErrSmallBuf
				}
				shift := 0
				done := false
				for l, b := range buf[i:] {
					if l == 9 && b > 1 {
						return i, muserrs.ErrOverflow
					}
					if b < 0x80 {
						v.Slice[j] = v.Slice[j] | uint(b)<<shift
						done = true
						i += l + 1
						break
					}
					v.Slice[j] = v.Slice[j] | uint(b&0x7F)<<shift
					shift += 7
				}
				if !done {
					return i, muserrs.ErrSmallBuf
				}
			}
			if err != nil {
				err = muserrs.NewSliceError(j, err)
				break
			}
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("Slice", err)
	}
	v.SlicePtr = new([]uint16)
	if buf[i] == 0 {
		i++
		v.SlicePtr = nil
	} else if buf[i] != 1 {
		i++
		return i, muserrs.ErrWrongByte
	} else {
		i++
		{
			var length int
			{
				var uv uint64
				{
					if i > len(buf)-1 {
						return i, muserrs.ErrSmallBuf
					}
					shift := 0
					done := false
					for l, b := range buf[i:] {
						if l == 9 && b > 1 {
							return i, muserrs.ErrOverflow
						}
						if b < 0x80 {
							uv = uv | uint64(b)<<shift
							done = true
							i += l + 1
							break
						}
						uv = uv | uint64(b&0x7F)<<shift
						shift += 7
					}
					if !done {
						return i, muserrs.ErrSmallBuf
					}
				}
				if uv&1 == 1 {
					uv = ^(uv >> 1)
				} else {
					uv = uv >> 1
				}
				length = int(uv)
			}
			if length < 0 {
				return i, muserrs.ErrNegativeLength
			}
			(*v.SlicePtr) = make([]uint16, length)
			for j := 0; j < length; j++ {
				{
					if i > len(buf)-1 {
						return i, muserrs.ErrSmallBuf
					}
					shift := 0
					done := false
					for l, b := range buf[i:] {
						if l == 2 && b > 3 {
							return i, muserrs.ErrOverflow
						}
						if b < 0x80 {
							(*v.SlicePtr)[j] = (*v.SlicePtr)[j] | uint16(b)<<shift
							done = true
							i += l + 1
							break
						}
						(*v.SlicePtr)[j] = (*v.SlicePtr)[j] | uint16(b&0x7F)<<shift
						shift += 7
					}
					if !done {
						return i, muserrs.ErrSmallBuf
					}
				}
				if err != nil {
					err = muserrs.NewSliceError(j, err)
					break
				}
			}
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("SlicePtr", err)
	}
	{
		tmp0 := new([]uint16)
		tmp1 := &tmp0
		v.SlicePtrPtrPtr = &tmp1
	}
	if buf[i] == 0 {
		i++
		v.SlicePtrPtrPtr = nil
	} else if buf[i] != 1 {
		i++
		return i, muserrs.ErrWrongByte
	} else {
		i++
		{
			var length int
			{
				var uv uint64
				{
					if i > len(buf)-1 {
						return i, muserrs.ErrSmallBuf
					}
					shift := 0
					done := false
					for l, b := range buf[i:] {
						if l == 9 && b > 1 {
							return i, muserrs.ErrOverflow
						}
						if b < 0x80 {
							uv = uv | uint64(b)<<shift
							done = true
							i += l + 1
							break
						}
						uv = uv | uint64(b&0x7F)<<shift
						shift += 7
					}
					if !done {
						return i, muserrs.ErrSmallBuf
					}
				}
				if uv&1 == 1 {
					uv = ^(uv >> 1)
				} else {
					uv = uv >> 1
				}
				length = int(uv)
			}
			if length < 0 {
				return i, muserrs.ErrNegativeLength
			}
			(***v.SlicePtrPtrPtr) = make([]uint16, length)
			for j := 0; j < length; j++ {
				{
					if i > len(buf)-1 {
						return i, muserrs.ErrSmallBuf
					}
					shift := 0
					done := false
					for l, b := range buf[i:] {
						if l == 2 && b > 3 {
							return i, muserrs.ErrOverflow
						}
						if b < 0x80 {
							(***v.SlicePtrPtrPtr)[j] = (***v.SlicePtrPtrPtr)[j] | uint16(b)<<shift
							done = true
							i += l + 1
							break
						}
						(***v.SlicePtrPtrPtr)[j] = (***v.SlicePtrPtrPtr)[j] | uint16(b&0x7F)<<shift
						shift += 7
					}
					if !done {
						return i, muserrs.ErrSmallBuf
					}
				}
				if err != nil {
					err = muserrs.NewSliceError(j, err)
					break
				}
			}
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("SlicePtrPtrPtr", err)
	}
	{
		for j := 0; j < 2; j++ {
			{
				var uv uint64
				{
					if i > len(buf)-1 {
						return i, muserrs.ErrSmallBuf
					}
					shift := 0
					done := false
					for l, b := range buf[i:] {
						if l == 9 && b > 1 {
							return i, muserrs.ErrOverflow
						}
						if b < 0x80 {
							uv = uv | uint64(b)<<shift
							done = true
							i += l + 1
							break
						}
						uv = uv | uint64(b&0x7F)<<shift
						shift += 7
					}
					if !done {
						return i, muserrs.ErrSmallBuf
					}
				}
				if uv&1 == 1 {
					uv = ^(uv >> 1)
				} else {
					uv = uv >> 1
				}
				v.Array[j] = int(uv)
			}
			if err != nil {
				err = muserrs.NewArrayError(j, err)
				break
			}
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("Array", err)
	}
	v.ArrayPtr = new([2]int32)
	if buf[i] == 0 {
		i++
		v.ArrayPtr = nil
	} else if buf[i] != 1 {
		i++
		return i, muserrs.ErrWrongByte
	} else {
		i++
		{
			for j := 0; j < 2; j++ {
				{
					var uv uint32
					{
						if i > len(buf)-1 {
							return i, muserrs.ErrSmallBuf
						}
						shift := 0
						done := false
						for l, b := range buf[i:] {
							if l == 4 && b > 15 {
								return i, muserrs.ErrOverflow
							}
							if b < 0x80 {
								uv = uv | uint32(b)<<shift
								done = true
								i += l + 1
								break
							}
							uv = uv | uint32(b&0x7F)<<shift
							shift += 7
						}
						if !done {
							return i, muserrs.ErrSmallBuf
						}
					}
					if uv&1 == 1 {
						uv = ^(uv >> 1)
					} else {
						uv = uv >> 1
					}
					(*v.ArrayPtr)[j] = int32(uv)
				}
				if err != nil {
					err = muserrs.NewArrayError(j, err)
					break
				}
			}
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("ArrayPtr", err)
	}
	{
		tmp0 := new([2]int32)
		tmp1 := &tmp0
		v.ArrayPtrPtrPtr = &tmp1
	}
	if buf[i] == 0 {
		i++
		v.ArrayPtrPtrPtr = nil
	} else if buf[i] != 1 {
		i++
		return i, muserrs.ErrWrongByte
	} else {
		i++
		{
			for j := 0; j < 2; j++ {
				{
					var uv uint32
					{
						if i > len(buf)-1 {
							return i, muserrs.ErrSmallBuf
						}
						shift := 0
						done := false
						for l, b := range buf[i:] {
							if l == 4 && b > 15 {
								return i, muserrs.ErrOverflow
							}
							if b < 0x80 {
								uv = uv | uint32(b)<<shift
								done = true
								i += l + 1
								break
							}
							uv = uv | uint32(b&0x7F)<<shift
							shift += 7
						}
						if !done {
							return i, muserrs.ErrSmallBuf
						}
					}
					if uv&1 == 1 {
						uv = ^(uv >> 1)
					} else {
						uv = uv >> 1
					}
					(***v.ArrayPtrPtrPtr)[j] = int32(uv)
				}
				if err != nil {
					err = muserrs.NewArrayError(j, err)
					break
				}
			}
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("ArrayPtrPtrPtr", err)
	}
	{
		var length int
		{
			var uv uint64
			{
				if i > len(buf)-1 {
					return i, muserrs.ErrSmallBuf
				}
				shift := 0
				done := false
				for l, b := range buf[i:] {
					if l == 9 && b > 1 {
						return i, muserrs.ErrOverflow
					}
					if b < 0x80 {
						uv = uv | uint64(b)<<shift
						done = true
						i += l + 1
						break
					}
					uv = uv | uint64(b&0x7F)<<shift
					shift += 7
				}
				if !done {
					return i, muserrs.ErrSmallBuf
				}
			}
			if uv&1 == 1 {
				uv = ^(uv >> 1)
			} else {
				uv = uv >> 1
			}
			length = int(uv)
		}
		if length < 0 {
			return i, muserrs.ErrNegativeLength
		}
		v.Map = make(map[string]int)
		for ; length > 0; length-- {
			var kem string
			var vlm int
			{
				var length int
				{
					var uv uint64
					{
						if i > len(buf)-1 {
							return i, muserrs.ErrSmallBuf
						}
						shift := 0
						done := false
						for l, b := range buf[i:] {
							if l == 9 && b > 1 {
								return i, muserrs.ErrOverflow
							}
							if b < 0x80 {
								uv = uv | uint64(b)<<shift
								done = true
								i += l + 1
								break
							}
							uv = uv | uint64(b&0x7F)<<shift
							shift += 7
						}
						if !done {
							return i, muserrs.ErrSmallBuf
						}
					}
					if uv&1 == 1 {
						uv = ^(uv >> 1)
					} else {
						uv = uv >> 1
					}
					length = int(uv)
				}
				if length < 0 {
					return i, muserrs.ErrNegativeLength
				}
				if len(buf) < i+length {
					return i, muserrs.ErrSmallBuf
				}
				kem = string(buf[i : i+length])
				i += length
			}
			if err != nil {
				err = muserrs.NewMapKeyError(kem, err)
				break
			}
			{
				var uv uint64
				{
					if i > len(buf)-1 {
						return i, muserrs.ErrSmallBuf
					}
					shift := 0
					done := false
					for l, b := range buf[i:] {
						if l == 9 && b > 1 {
							return i, muserrs.ErrOverflow
						}
						if b < 0x80 {
							uv = uv | uint64(b)<<shift
							done = true
							i += l + 1
							break
						}
						uv = uv | uint64(b&0x7F)<<shift
						shift += 7
					}
					if !done {
						return i, muserrs.ErrSmallBuf
					}
				}
				if uv&1 == 1 {
					uv = ^(uv >> 1)
				} else {
					uv = uv >> 1
				}
				vlm = int(uv)
			}
			if err != nil {
				err = muserrs.NewMapValueError(kem, vlm, err)
				break
			}
			(v.Map)[kem] = vlm
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("Map", err)
	}
	v.MapPtr = new(map[string]int)
	if buf[i] == 0 {
		i++
		v.MapPtr = nil
	} else if buf[i] != 1 {
		i++
		return i, muserrs.ErrWrongByte
	} else {
		i++
		{
			var length int
			{
				var uv uint64
				{
					if i > len(buf)-1 {
						return i, muserrs.ErrSmallBuf
					}
					shift := 0
					done := false
					for l, b := range buf[i:] {
						if l == 9 && b > 1 {
							return i, muserrs.ErrOverflow
						}
						if b < 0x80 {
							uv = uv | uint64(b)<<shift
							done = true
							i += l + 1
							break
						}
						uv = uv | uint64(b&0x7F)<<shift
						shift += 7
					}
					if !done {
						return i, muserrs.ErrSmallBuf
					}
				}
				if uv&1 == 1 {
					uv = ^(uv >> 1)
				} else {
					uv = uv >> 1
				}
				length = int(uv)
			}
			if length < 0 {
				return i, muserrs.ErrNegativeLength
			}
			(*v.MapPtr) = make(map[string]int)
			for ; length > 0; length-- {
				var kem string
				var vlm int
				{
					var length int
					{
						var uv uint64
						{
							if i > len(buf)-1 {
								return i, muserrs.ErrSmallBuf
							}
							shift := 0
							done := false
							for l, b := range buf[i:] {
								if l == 9 && b > 1 {
									return i, muserrs.ErrOverflow
								}
								if b < 0x80 {
									uv = uv | uint64(b)<<shift
									done = true
									i += l + 1
									break
								}
								uv = uv | uint64(b&0x7F)<<shift
								shift += 7
							}
							if !done {
								return i, muserrs.ErrSmallBuf
							}
						}
						if uv&1 == 1 {
							uv = ^(uv >> 1)
						} else {
							uv = uv >> 1
						}
						length = int(uv)
					}
					if length < 0 {
						return i, muserrs.ErrNegativeLength
					}
					if len(buf) < i+length {
						return i, muserrs.ErrSmallBuf
					}
					kem = string(buf[i : i+length])
					i += length
				}
				if err != nil {
					err = muserrs.NewMapKeyError(kem, err)
					break
				}
				{
					var uv uint64
					{
						if i > len(buf)-1 {
							return i, muserrs.ErrSmallBuf
						}
						shift := 0
						done := false
						for l, b := range buf[i:] {
							if l == 9 && b > 1 {
								return i, muserrs.ErrOverflow
							}
							if b < 0x80 {
								uv = uv | uint64(b)<<shift
								done = true
								i += l + 1
								break
							}
							uv = uv | uint64(b&0x7F)<<shift
							shift += 7
						}
						if !done {
							return i, muserrs.ErrSmallBuf
						}
					}
					if uv&1 == 1 {
						uv = ^(uv >> 1)
					} else {
						uv = uv >> 1
					}
					vlm = int(uv)
				}
				if err != nil {
					err = muserrs.NewMapValueError(kem, vlm, err)
					break
				}
				(*v.MapPtr)[kem] = vlm
			}
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("MapPtr", err)
	}
	{
		tmp0 := new(map[string]int)
		tmp1 := &tmp0
		v.MapPtrPtrPtr = &tmp1
	}
	if buf[i] == 0 {
		i++
		v.MapPtrPtrPtr = nil
	} else if buf[i] != 1 {
		i++
		return i, muserrs.ErrWrongByte
	} else {
		i++
		{
			var length int
			{
				var uv uint64
				{
					if i > len(buf)-1 {
						return i, muserrs.ErrSmallBuf
					}
					shift := 0
					done := false
					for l, b := range buf[i:] {
						if l == 9 && b > 1 {
							return i, muserrs.ErrOverflow
						}
						if b < 0x80 {
							uv = uv | uint64(b)<<shift
							done = true
							i += l + 1
							break
						}
						uv = uv | uint64(b&0x7F)<<shift
						shift += 7
					}
					if !done {
						return i, muserrs.ErrSmallBuf
					}
				}
				if uv&1 == 1 {
					uv = ^(uv >> 1)
				} else {
					uv = uv >> 1
				}
				length = int(uv)
			}
			if length < 0 {
				return i, muserrs.ErrNegativeLength
			}
			(***v.MapPtrPtrPtr) = make(map[string]int)
			for ; length > 0; length-- {
				var kem string
				var vlm int
				{
					var length int
					{
						var uv uint64
						{
							if i > len(buf)-1 {
								return i, muserrs.ErrSmallBuf
							}
							shift := 0
							done := false
							for l, b := range buf[i:] {
								if l == 9 && b > 1 {
									return i, muserrs.ErrOverflow
								}
								if b < 0x80 {
									uv = uv | uint64(b)<<shift
									done = true
									i += l + 1
									break
								}
								uv = uv | uint64(b&0x7F)<<shift
								shift += 7
							}
							if !done {
								return i, muserrs.ErrSmallBuf
							}
						}
						if uv&1 == 1 {
							uv = ^(uv >> 1)
						} else {
							uv = uv >> 1
						}
						length = int(uv)
					}
					if length < 0 {
						return i, muserrs.ErrNegativeLength
					}
					if len(buf) < i+length {
						return i, muserrs.ErrSmallBuf
					}
					kem = string(buf[i : i+length])
					i += length
				}
				if err != nil {
					err = muserrs.NewMapKeyError(kem, err)
					break
				}
				{
					var uv uint64
					{
						if i > len(buf)-1 {
							return i, muserrs.ErrSmallBuf
						}
						shift := 0
						done := false
						for l, b := range buf[i:] {
							if l == 9 && b > 1 {
								return i, muserrs.ErrOverflow
							}
							if b < 0x80 {
								uv = uv | uint64(b)<<shift
								done = true
								i += l + 1
								break
							}
							uv = uv | uint64(b&0x7F)<<shift
							shift += 7
						}
						if !done {
							return i, muserrs.ErrSmallBuf
						}
					}
					if uv&1 == 1 {
						uv = ^(uv >> 1)
					} else {
						uv = uv >> 1
					}
					vlm = int(uv)
				}
				if err != nil {
					err = muserrs.NewMapValueError(kem, vlm, err)
					break
				}
				(***v.MapPtrPtrPtr)[kem] = vlm
			}
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("MapPtrPtrPtr", err)
	}
	{
		var sv SimpleStructType
		si := 0
		si, err = sv.Unmarshal(buf[i:])
		if err == nil {
			v.Struct = sv
			i += si
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("Struct", err)
	}
	v.StructPtr = new(SimpleStructType)
	if buf[i] == 0 {
		i++
		v.StructPtr = nil
	} else if buf[i] != 1 {
		i++
		return i, muserrs.ErrWrongByte
	} else {
		i++
		{
			var sv SimpleStructType
			si := 0
			si, err = sv.Unmarshal(buf[i:])
			if err == nil {
				(*v.StructPtr) = sv
				i += si
			}
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("StructPtr", err)
	}
	{
		tmp0 := new(SimpleStructType)
		tmp1 := &tmp0
		v.StructPtrPtrPtr = &tmp1
	}
	if buf[i] == 0 {
		i++
		v.StructPtrPtrPtr = nil
	} else if buf[i] != 1 {
		i++
		return i, muserrs.ErrWrongByte
	} else {
		i++
		{
			var sv SimpleStructType
			si := 0
			si, err = sv.Unmarshal(buf[i:])
			if err == nil {
				(***v.StructPtrPtrPtr) = sv
				i += si
			}
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("StructPtrPtrPtr", err)
	}
	{
		for j := 0; j < 2; j++ {
			{
				var length int
				{
					var uv uint64
					{
						if i > len(buf)-1 {
							return i, muserrs.ErrSmallBuf
						}
						shift := 0
						done := false
						for l, b := range buf[i:] {
							if l == 9 && b > 1 {
								return i, muserrs.ErrOverflow
							}
							if b < 0x80 {
								uv = uv | uint64(b)<<shift
								done = true
								i += l + 1
								break
							}
							uv = uv | uint64(b&0x7F)<<shift
							shift += 7
						}
						if !done {
							return i, muserrs.ErrSmallBuf
						}
					}
					if uv&1 == 1 {
						uv = ^(uv >> 1)
					} else {
						uv = uv >> 1
					}
					length = int(uv)
				}
				if length < 0 {
					return i, muserrs.ErrNegativeLength
				}
				v.Tricky[j] = make(map[[2]IntAlias]map[StringAlias][2]string)
				for ; length > 0; length-- {
					var kem [2]IntAlias
					var vlm map[StringAlias][2]string
					{
						for j := 0; j < 2; j++ {
							{
								var sv IntAlias
								si := 0
								si, err = sv.Unmarshal(buf[i:])
								if err == nil {
									kem[j] = sv
									i += si
								}
							}
							if err != nil {
								err = muserrs.NewArrayError(j, err)
								break
							}
						}
					}
					if err != nil {
						err = muserrs.NewMapKeyError(kem, err)
						break
					}
					{
						var length int
						{
							var uv uint64
							{
								if i > len(buf)-1 {
									return i, muserrs.ErrSmallBuf
								}
								shift := 0
								done := false
								for l, b := range buf[i:] {
									if l == 9 && b > 1 {
										return i, muserrs.ErrOverflow
									}
									if b < 0x80 {
										uv = uv | uint64(b)<<shift
										done = true
										i += l + 1
										break
									}
									uv = uv | uint64(b&0x7F)<<shift
									shift += 7
								}
								if !done {
									return i, muserrs.ErrSmallBuf
								}
							}
							if uv&1 == 1 {
								uv = ^(uv >> 1)
							} else {
								uv = uv >> 1
							}
							length = int(uv)
						}
						if length < 0 {
							return i, muserrs.ErrNegativeLength
						}
						vlm = make(map[StringAlias][2]string)
						for ; length > 0; length-- {
							var kemm StringAlias
							var vlmm [2]string
							{
								var sv StringAlias
								si := 0
								si, err = sv.Unmarshal(buf[i:])
								if err == nil {
									kemm = sv
									i += si
								}
							}
							if err != nil {
								err = muserrs.NewMapKeyError(kemm, err)
								break
							}
							{
								for j := 0; j < 2; j++ {
									{
										var length int
										{
											var uv uint64
											{
												if i > len(buf)-1 {
													return i, muserrs.ErrSmallBuf
												}
												shift := 0
												done := false
												for l, b := range buf[i:] {
													if l == 9 && b > 1 {
														return i, muserrs.ErrOverflow
													}
													if b < 0x80 {
														uv = uv | uint64(b)<<shift
														done = true
														i += l + 1
														break
													}
													uv = uv | uint64(b&0x7F)<<shift
													shift += 7
												}
												if !done {
													return i, muserrs.ErrSmallBuf
												}
											}
											if uv&1 == 1 {
												uv = ^(uv >> 1)
											} else {
												uv = uv >> 1
											}
											length = int(uv)
										}
										if length < 0 {
											return i, muserrs.ErrNegativeLength
										}
										if len(buf) < i+length {
											return i, muserrs.ErrSmallBuf
										}
										vlmm[j] = string(buf[i : i+length])
										i += length
									}
									if err != nil {
										err = muserrs.NewArrayError(j, err)
										break
									}
								}
							}
							if err != nil {
								err = muserrs.NewMapValueError(kemm, vlmm, err)
								break
							}
							(vlm)[kemm] = vlmm
						}
					}
					if err != nil {
						err = muserrs.NewMapValueError(kem, vlm, err)
						break
					}
					(v.Tricky[j])[kem] = vlm
				}
			}
			if err != nil {
				err = muserrs.NewArrayError(j, err)
				break
			}
		}
	}
	if err != nil {
		return i, muserrs.NewFieldError("Tricky", err)
	}
	return i, err
}

// Size returns the size of the MUS-encoded v.
func (v StructType) Size() int {
	size := 0
	{
		for v.Uint >= 0x80 {
			v.Uint >>= 7
			size++
		}
		size++
	}
	{
		for v.Uint16 >= 0x80 {
			v.Uint16 >>= 7
			size++
		}
		size++
	}
	{
		for v.Uint32 >= 0x80 {
			v.Uint32 >>= 7
			size++
		}
		size++
	}
	{
		for v.Uint64 >= 0x80 {
			v.Uint64 >>= 7
			size++
		}
		size++
	}
	size++
	if v.UintPtr != nil {
		{
			tmp := (*v.UintPtr)
			for tmp >= 0x80 {
				tmp >>= 7
				size++
			}
			size++
		}
	}
	size++
	if v.UintPtrPtrPtr != nil {
		{
			tmp := (***v.UintPtrPtrPtr)
			for tmp >= 0x80 {
				tmp >>= 7
				size++
			}
			size++
		}
	}
	{
		uv := uint64(v.Int<<1) ^ uint64(v.Int>>63)
		{
			for uv >= 0x80 {
				uv >>= 7
				size++
			}
			size++
		}
	}
	{
		_ = v.Int8
		size++
	}
	{
		uv := uint16(v.Int16<<1) ^ uint16(v.Int16>>15)
		{
			for uv >= 0x80 {
				uv >>= 7
				size++
			}
			size++
		}
	}
	{
		uv := uint32(v.Int32<<1) ^ uint32(v.Int32>>31)
		{
			for uv >= 0x80 {
				uv >>= 7
				size++
			}
			size++
		}
	}
	{
		uv := uint64(v.Int64<<1) ^ uint64(v.Int64>>63)
		{
			for uv >= 0x80 {
				uv >>= 7
				size++
			}
			size++
		}
	}
	size++
	if v.IntPtr != nil {
		{
			uv := uint64((*v.IntPtr)<<1) ^ uint64((*v.IntPtr)>>63)
			{
				for uv >= 0x80 {
					uv >>= 7
					size++
				}
				size++
			}
		}
	}
	size++
	if v.IntPtrPtrPtr != nil {
		{
			uv := uint64((***v.IntPtrPtrPtr)<<1) ^ uint64((***v.IntPtrPtrPtr)>>63)
			{
				for uv >= 0x80 {
					uv >>= 7
					size++
				}
				size++
			}
		}
	}
	size++
	if v.IntAliasPtr != nil {
		{
			ss := (*v.IntAliasPtr).Size()
			size += ss
		}
	}
	{
		length := len(v.String)
		{
			uv := uint64(length<<1) ^ uint64(length>>63)
			{
				for uv >= 0x80 {
					uv >>= 7
					size++
				}
				size++
			}
		}
		size += len(v.String)
	}
	size++
	if v.StringPtr != nil {
		{
			length := len((*v.StringPtr))
			{
				uv := uint64(length<<1) ^ uint64(length>>63)
				{
					for uv >= 0x80 {
						uv >>= 7
						size++
					}
					size++
				}
			}
			size += len((*v.StringPtr))
		}
	}
	size++
	if v.StringPtrPtrPtr != nil {
		{
			length := len((***v.StringPtrPtrPtr))
			{
				uv := uint64(length<<1) ^ uint64(length>>63)
				{
					for uv >= 0x80 {
						uv >>= 7
						size++
					}
					size++
				}
			}
			size += len((***v.StringPtrPtrPtr))
		}
	}
	{
		_ = v.Byte
		size++
	}
	size++
	if v.BytePtr != nil {
		{
			_ = v.BytePtr
			size++
		}
	}
	size++
	if v.BytePtrPtrPtr != nil {
		{
			_ = v.BytePtrPtrPtr
			size++
		}
	}
	{
		_ = v.Bool
		size++
	}
	size++
	if v.BoolPtr != nil {
		{
			_ = v.BoolPtr
			size++
		}
	}
	size++
	if v.BoolPtrPtrPtr != nil {
		{
			_ = v.BoolPtrPtrPtr
			size++
		}
	}
	{
		length := len(v.Slice)
		{
			uv := uint64(length<<1) ^ uint64(length>>63)
			{
				for uv >= 0x80 {
					uv >>= 7
					size++
				}
				size++
			}
		}
		for _, el := range v.Slice {
			{
				for el >= 0x80 {
					el >>= 7
					size++
				}
				size++
			}
		}
	}
	size++
	if v.SlicePtr != nil {
		{
			length := len((*v.SlicePtr))
			{
				uv := uint64(length<<1) ^ uint64(length>>63)
				{
					for uv >= 0x80 {
						uv >>= 7
						size++
					}
					size++
				}
			}
			for _, el := range *v.SlicePtr {
				{
					for el >= 0x80 {
						el >>= 7
						size++
					}
					size++
				}
			}
		}
	}
	size++
	if v.SlicePtrPtrPtr != nil {
		{
			length := len((***v.SlicePtrPtrPtr))
			{
				uv := uint64(length<<1) ^ uint64(length>>63)
				{
					for uv >= 0x80 {
						uv >>= 7
						size++
					}
					size++
				}
			}
			for _, el := range ***v.SlicePtrPtrPtr {
				{
					for el >= 0x80 {
						el >>= 7
						size++
					}
					size++
				}
			}
		}
	}
	{
		for _, item := range v.Array {
			{
				uv := uint64(item<<1) ^ uint64(item>>63)
				{
					for uv >= 0x80 {
						uv >>= 7
						size++
					}
					size++
				}
			}
		}
	}
	size++
	if v.ArrayPtr != nil {
		{
			for _, item := range *v.ArrayPtr {
				{
					uv := uint32(item<<1) ^ uint32(item>>31)
					{
						for uv >= 0x80 {
							uv >>= 7
							size++
						}
						size++
					}
				}
			}
		}
	}
	size++
	if v.ArrayPtrPtrPtr != nil {
		{
			for _, item := range ***v.ArrayPtrPtrPtr {
				{
					uv := uint32(item<<1) ^ uint32(item>>31)
					{
						for uv >= 0x80 {
							uv >>= 7
							size++
						}
						size++
					}
				}
			}
		}
	}
	{
		length := len(v.Map)
		{
			uv := uint64(length<<1) ^ uint64(length>>63)
			{
				for uv >= 0x80 {
					uv >>= 7
					size++
				}
				size++
			}
		}
		for ke, vl := range v.Map {
			{
				length := len(ke)
				{
					uv := uint64(length<<1) ^ uint64(length>>63)
					{
						for uv >= 0x80 {
							uv >>= 7
							size++
						}
						size++
					}
				}
				size += len(ke)
			}
			{
				uv := uint64(vl<<1) ^ uint64(vl>>63)
				{
					for uv >= 0x80 {
						uv >>= 7
						size++
					}
					size++
				}
			}
		}
	}
	size++
	if v.MapPtr != nil {
		{
			length := len((*v.MapPtr))
			{
				uv := uint64(length<<1) ^ uint64(length>>63)
				{
					for uv >= 0x80 {
						uv >>= 7
						size++
					}
					size++
				}
			}
			for ke, vl := range *v.MapPtr {
				{
					length := len(ke)
					{
						uv := uint64(length<<1) ^ uint64(length>>63)
						{
							for uv >= 0x80 {
								uv >>= 7
								size++
							}
							size++
						}
					}
					size += len(ke)
				}
				{
					uv := uint64(vl<<1) ^ uint64(vl>>63)
					{
						for uv >= 0x80 {
							uv >>= 7
							size++
						}
						size++
					}
				}
			}
		}
	}
	size++
	if v.MapPtrPtrPtr != nil {
		{
			length := len((***v.MapPtrPtrPtr))
			{
				uv := uint64(length<<1) ^ uint64(length>>63)
				{
					for uv >= 0x80 {
						uv >>= 7
						size++
					}
					size++
				}
			}
			for ke, vl := range ***v.MapPtrPtrPtr {
				{
					length := len(ke)
					{
						uv := uint64(length<<1) ^ uint64(length>>63)
						{
							for uv >= 0x80 {
								uv >>= 7
								size++
							}
							size++
						}
					}
					size += len(ke)
				}
				{
					uv := uint64(vl<<1) ^ uint64(vl>>63)
					{
						for uv >= 0x80 {
							uv >>= 7
							size++
						}
						size++
					}
				}
			}
		}
	}
	{
		ss := v.Struct.Size()
		size += ss
	}
	size++
	if v.StructPtr != nil {
		{
			ss := (*v.StructPtr).Size()
			size += ss
		}
	}
	size++
	if v.StructPtrPtrPtr != nil {
		{
			ss := (***v.StructPtrPtrPtr).Size()
			size += ss
		}
	}
	{
		for _, item := range v.Tricky {
			{
				length := len(item)
				{
					uv := uint64(length<<1) ^ uint64(length>>63)
					{
						for uv >= 0x80 {
							uv >>= 7
							size++
						}
						size++
					}
				}
				for ke, vl := range item {
					{
						for _, item := range ke {
							{
								ss := item.Size()
								size += ss
							}
						}
					}
					{
						length := len(vl)
						{
							uv := uint64(length<<1) ^ uint64(length>>63)
							{
								for uv >= 0x80 {
									uv >>= 7
									size++
								}
								size++
							}
						}
						for ke, vl := range vl {
							{
								ss := ke.Size()
								size += ss
							}
							{
								for _, item := range vl {
									{
										length := len(item)
										{
											uv := uint64(length<<1) ^ uint64(length>>63)
											{
												for uv >= 0x80 {
													uv >>= 7
													size++
												}
												size++
											}
										}
										size += len(item)
									}
								}
							}
						}
					}
				}
			}
		}
	}
	return size
}
