// Code generated by musgen. DO NOT EDIT.

package musgen

import "github.com/ymz-ncnk/musgo/v2/errs"

// Marshal fills buf with the MUS encoding of v.
func (v ValidStructType) Marshal(buf []byte) int {
	i := 0
	{
		for v.Uint64 >= 0x80 {
			buf[i] = byte(v.Uint64) | 0x80
			v.Uint64 >>= 7
			i++
		}
		buf[i] = byte(v.Uint64)
		i++
	}
	{
		buf[i] = byte(v.Int8)
		i++
	}
	{
		length := len(v.String)
		{
			uv := uint64(length)
			if length < 0 {
				uv = ^(uv << 1)
			} else {
				uv = uv << 1
			}
			{
				for uv >= 0x80 {
					buf[i] = byte(uv) | 0x80
					uv >>= 7
					i++
				}
				buf[i] = byte(uv)
				i++
			}
		}
		if len(buf[i:]) < length {
			panic(errs.ErrSmallBuf)
		}
		i += copy(buf[i:], v.String)
	}
	if v.StringPtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			length := len((*v.StringPtr))
			{
				uv := uint64(length)
				if length < 0 {
					uv = ^(uv << 1)
				} else {
					uv = uv << 1
				}
				{
					for uv >= 0x80 {
						buf[i] = byte(uv) | 0x80
						uv >>= 7
						i++
					}
					buf[i] = byte(uv)
					i++
				}
			}
			if len(buf[i:]) < length {
				panic(errs.ErrSmallBuf)
			}
			i += copy(buf[i:], (*v.StringPtr))
		}
	}
	{
		buf[i] = byte(v.Byte)
		i++
	}
	{
		if v.Bool {
			buf[i] = 0x01
		} else {
			buf[i] = 0x00
		}
		i++
	}
	{
		length := len(v.Slice)
		{
			uv := uint64(length)
			if length < 0 {
				uv = ^(uv << 1)
			} else {
				uv = uv << 1
			}
			{
				for uv >= 0x80 {
					buf[i] = byte(uv) | 0x80
					uv >>= 7
					i++
				}
				buf[i] = byte(uv)
				i++
			}
		}
		for _, el := range v.Slice {
			{
				for el >= 0x80 {
					buf[i] = byte(el) | 0x80
					el >>= 7
					i++
				}
				buf[i] = byte(el)
				i++
			}
		}
	}
	if v.SlicePtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			length := len((*v.SlicePtr))
			{
				uv := uint64(length)
				if length < 0 {
					uv = ^(uv << 1)
				} else {
					uv = uv << 1
				}
				{
					for uv >= 0x80 {
						buf[i] = byte(uv) | 0x80
						uv >>= 7
						i++
					}
					buf[i] = byte(uv)
					i++
				}
			}
			for _, el := range *v.SlicePtr {
				{
					for el >= 0x80 {
						buf[i] = byte(el) | 0x80
						el >>= 7
						i++
					}
					buf[i] = byte(el)
					i++
				}
			}
		}
	}
	{
		for _, item := range v.Array {
			{
				uv := uint64(item)
				if item < 0 {
					uv = ^(uv << 1)
				} else {
					uv = uv << 1
				}
				{
					for uv >= 0x80 {
						buf[i] = byte(uv) | 0x80
						uv >>= 7
						i++
					}
					buf[i] = byte(uv)
					i++
				}
			}
		}
	}
	if v.ArrayPtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			for _, item := range *v.ArrayPtr {
				{
					uv := uint32(item)
					if item < 0 {
						uv = ^(uv << 1)
					} else {
						uv = uv << 1
					}
					{
						for uv >= 0x80 {
							buf[i] = byte(uv) | 0x80
							uv >>= 7
							i++
						}
						buf[i] = byte(uv)
						i++
					}
				}
			}
		}
	}
	{
		length := len(v.Map)
		{
			uv := uint64(length)
			if length < 0 {
				uv = ^(uv << 1)
			} else {
				uv = uv << 1
			}
			{
				for uv >= 0x80 {
					buf[i] = byte(uv) | 0x80
					uv >>= 7
					i++
				}
				buf[i] = byte(uv)
				i++
			}
		}
		for ke, vl := range v.Map {
			{
				length := len(ke)
				{
					uv := uint64(length)
					if length < 0 {
						uv = ^(uv << 1)
					} else {
						uv = uv << 1
					}
					{
						for uv >= 0x80 {
							buf[i] = byte(uv) | 0x80
							uv >>= 7
							i++
						}
						buf[i] = byte(uv)
						i++
					}
				}
				if len(buf[i:]) < length {
					panic(errs.ErrSmallBuf)
				}
				i += copy(buf[i:], ke)
			}
			{
				uv := uint64(vl)
				if vl < 0 {
					uv = ^(uv << 1)
				} else {
					uv = uv << 1
				}
				{
					for uv >= 0x80 {
						buf[i] = byte(uv) | 0x80
						uv >>= 7
						i++
					}
					buf[i] = byte(uv)
					i++
				}
			}
		}
	}
	if v.MapPtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			length := len((*v.MapPtr))
			{
				uv := uint64(length)
				if length < 0 {
					uv = ^(uv << 1)
				} else {
					uv = uv << 1
				}
				{
					for uv >= 0x80 {
						buf[i] = byte(uv) | 0x80
						uv >>= 7
						i++
					}
					buf[i] = byte(uv)
					i++
				}
			}
			for ke, vl := range *v.MapPtr {
				{
					length := len(ke)
					{
						uv := uint64(length)
						if length < 0 {
							uv = ^(uv << 1)
						} else {
							uv = uv << 1
						}
						{
							for uv >= 0x80 {
								buf[i] = byte(uv) | 0x80
								uv >>= 7
								i++
							}
							buf[i] = byte(uv)
							i++
						}
					}
					if len(buf[i:]) < length {
						panic(errs.ErrSmallBuf)
					}
					i += copy(buf[i:], ke)
				}
				{
					uv := uint64(vl)
					if vl < 0 {
						uv = ^(uv << 1)
					} else {
						uv = uv << 1
					}
					{
						for uv >= 0x80 {
							buf[i] = byte(uv) | 0x80
							uv >>= 7
							i++
						}
						buf[i] = byte(uv)
						i++
					}
				}
			}
		}
	}
	{
		si := v.Struct.Marshal(buf[i:])
		i += si
	}
	if v.StructPtr == nil {
		buf[i] = 0
		i++
	} else {
		buf[i] = 1
		i++
		{
			si := (*v.StructPtr).Marshal(buf[i:])
			i += si
		}
	}
	return i
}

// Unmarshal parses the MUS-encoded buf, and sets the result to *v.
func (v *ValidStructType) Unmarshal(buf []byte) (int, error) {
	i := 0
	var err error
	{
		if i > len(buf)-1 {
			return i, errs.ErrSmallBuf
		}
		shift := 0
		done := false
		for l, b := range buf[i:] {
			if l == 9 && b > 1 {
				return i, errs.ErrOverflow
			}
			if b < 0x80 {
				v.Uint64 = v.Uint64 | uint64(b)<<shift
				done = true
				i += l + 1
				break
			}
			v.Uint64 = v.Uint64 | uint64(b&0x7F)<<shift
			shift += 7
		}
		if !done {
			return i, errs.ErrSmallBuf
		}
	}
	if err == nil {
		err = BiggerThanTenUint64(v.Uint64)
	}
	if err != nil {
		return i, errs.NewFieldError("Uint64", err)
	}
	{
		if i > len(buf)-1 {
			return i, errs.ErrSmallBuf
		}
		v.Int8 = int8(buf[i])
		i++
	}
	if err == nil {
		err = BiggerThanTenInt8(v.Int8)
	}
	if err != nil {
		return i, errs.NewFieldError("Int8", err)
	}
	{
		var length int
		{
			var uv uint64
			{
				if i > len(buf)-1 {
					return i, errs.ErrSmallBuf
				}
				shift := 0
				done := false
				for l, b := range buf[i:] {
					if l == 9 && b > 1 {
						return i, errs.ErrOverflow
					}
					if b < 0x80 {
						uv = uv | uint64(b)<<shift
						done = true
						i += l + 1
						break
					}
					uv = uv | uint64(b&0x7F)<<shift
					shift += 7
				}
				if !done {
					return i, errs.ErrSmallBuf
				}
			}
			if uv&1 == 1 {
				uv = ^(uv >> 1)
			} else {
				uv = uv >> 1
			}
			length = int(uv)
		}
		if length < 0 {
			return i, errs.ErrNegativeLength
		}
		if len(buf) < i+length {
			return i, errs.ErrSmallBuf
		}
		if length > 10 {
			err = errs.ErrMaxLengthExceeded
		} else {
			v.String = string(buf[i : i+length])
			i += length
		}
	}
	if err == nil {
		err = NotEmptyString(v.String)
	}
	if err != nil {
		return i, errs.NewFieldError("String", err)
	}
	v.StringPtr = new(string)
	if buf[i] == 0 {
		i++
		v.StringPtr = nil
	} else if buf[i] != 1 {
		i++
		return i, errs.ErrWrongByte
	} else {
		i++
		{
			var length int
			{
				var uv uint64
				{
					if i > len(buf)-1 {
						return i, errs.ErrSmallBuf
					}
					shift := 0
					done := false
					for l, b := range buf[i:] {
						if l == 9 && b > 1 {
							return i, errs.ErrOverflow
						}
						if b < 0x80 {
							uv = uv | uint64(b)<<shift
							done = true
							i += l + 1
							break
						}
						uv = uv | uint64(b&0x7F)<<shift
						shift += 7
					}
					if !done {
						return i, errs.ErrSmallBuf
					}
				}
				if uv&1 == 1 {
					uv = ^(uv >> 1)
				} else {
					uv = uv >> 1
				}
				length = int(uv)
			}
			if length < 0 {
				return i, errs.ErrNegativeLength
			}
			if len(buf) < i+length {
				return i, errs.ErrSmallBuf
			}
			if length > 10 {
				err = errs.ErrMaxLengthExceeded
			} else {
				(*v.StringPtr) = string(buf[i : i+length])
				i += length
			}
		}
	}
	if err == nil {
		err = NotNilString(v.StringPtr)
	}
	if err != nil {
		return i, errs.NewFieldError("StringPtr", err)
	}
	{
		if i > len(buf)-1 {
			return i, errs.ErrSmallBuf
		}
		v.Byte = uint8(buf[i])
		i++
	}
	if err == nil {
		err = BiggerThanTenByte(v.Byte)
	}
	if err != nil {
		return i, errs.NewFieldError("Byte", err)
	}
	{
		if i > len(buf)-1 {
			return i, errs.ErrSmallBuf
		}
		if buf[i] == 0x01 {
			v.Bool = true
			i++
		} else if buf[i] == 0x00 {
			v.Bool = false
			i++
		} else {
			err = errs.ErrWrongByte
		}
	}
	if err == nil {
		err = PositiveBool(v.Bool)
	}
	if err != nil {
		return i, errs.NewFieldError("Bool", err)
	}
	{
		var length int
		{
			var uv uint64
			{
				if i > len(buf)-1 {
					return i, errs.ErrSmallBuf
				}
				shift := 0
				done := false
				for l, b := range buf[i:] {
					if l == 9 && b > 1 {
						return i, errs.ErrOverflow
					}
					if b < 0x80 {
						uv = uv | uint64(b)<<shift
						done = true
						i += l + 1
						break
					}
					uv = uv | uint64(b&0x7F)<<shift
					shift += 7
				}
				if !done {
					return i, errs.ErrSmallBuf
				}
			}
			if uv&1 == 1 {
				uv = ^(uv >> 1)
			} else {
				uv = uv >> 1
			}
			length = int(uv)
		}
		if length < 0 {
			return i, errs.ErrNegativeLength
		}
		if length > 8 {
			err = errs.ErrMaxLengthExceeded
		} else {
			v.Slice = make([]uint, length)
			for j := 0; j < length; j++ {
				{
					if i > len(buf)-1 {
						return i, errs.ErrSmallBuf
					}
					shift := 0
					done := false
					for l, b := range buf[i:] {
						if l == 9 && b > 1 {
							return i, errs.ErrOverflow
						}
						if b < 0x80 {
							v.Slice[j] = v.Slice[j] | uint(b)<<shift
							done = true
							i += l + 1
							break
						}
						v.Slice[j] = v.Slice[j] | uint(b&0x7F)<<shift
						shift += 7
					}
					if !done {
						return i, errs.ErrSmallBuf
					}
				}
				if err == nil {
					err = BiggerThanTenUint(v.Slice[j])
				}
				if err != nil {
					err = errs.NewSliceError(j, err)
					break
				}
			}
		}
	}
	if err == nil {
		err = UintSliceSumBiggerThanTen(v.Slice)
	}
	if err != nil {
		return i, errs.NewFieldError("Slice", err)
	}
	v.SlicePtr = new([]uint16)
	if buf[i] == 0 {
		i++
		v.SlicePtr = nil
	} else if buf[i] != 1 {
		i++
		return i, errs.ErrWrongByte
	} else {
		i++
		{
			var length int
			{
				var uv uint64
				{
					if i > len(buf)-1 {
						return i, errs.ErrSmallBuf
					}
					shift := 0
					done := false
					for l, b := range buf[i:] {
						if l == 9 && b > 1 {
							return i, errs.ErrOverflow
						}
						if b < 0x80 {
							uv = uv | uint64(b)<<shift
							done = true
							i += l + 1
							break
						}
						uv = uv | uint64(b&0x7F)<<shift
						shift += 7
					}
					if !done {
						return i, errs.ErrSmallBuf
					}
				}
				if uv&1 == 1 {
					uv = ^(uv >> 1)
				} else {
					uv = uv >> 1
				}
				length = int(uv)
			}
			if length < 0 {
				return i, errs.ErrNegativeLength
			}
			(*v.SlicePtr) = make([]uint16, length)
			for j := 0; j < length; j++ {
				{
					if i > len(buf)-1 {
						return i, errs.ErrSmallBuf
					}
					shift := 0
					done := false
					for l, b := range buf[i:] {
						if l == 2 && b > 3 {
							return i, errs.ErrOverflow
						}
						if b < 0x80 {
							(*v.SlicePtr)[j] = (*v.SlicePtr)[j] | uint16(b)<<shift
							done = true
							i += l + 1
							break
						}
						(*v.SlicePtr)[j] = (*v.SlicePtr)[j] | uint16(b&0x7F)<<shift
						shift += 7
					}
					if !done {
						return i, errs.ErrSmallBuf
					}
				}
				if err == nil {
					err = BiggerThanTenUint16((*v.SlicePtr)[j])
				}
				if err != nil {
					err = errs.NewSliceError(j, err)
					break
				}
			}
		}
	}
	if err == nil {
		err = Uint16SlicePtrSumBiggerThanTen(v.SlicePtr)
	}
	if err != nil {
		return i, errs.NewFieldError("SlicePtr", err)
	}
	{
		for j := 0; j < 2; j++ {
			{
				var uv uint64
				{
					if i > len(buf)-1 {
						return i, errs.ErrSmallBuf
					}
					shift := 0
					done := false
					for l, b := range buf[i:] {
						if l == 9 && b > 1 {
							return i, errs.ErrOverflow
						}
						if b < 0x80 {
							uv = uv | uint64(b)<<shift
							done = true
							i += l + 1
							break
						}
						uv = uv | uint64(b&0x7F)<<shift
						shift += 7
					}
					if !done {
						return i, errs.ErrSmallBuf
					}
				}
				if uv&1 == 1 {
					uv = ^(uv >> 1)
				} else {
					uv = uv >> 1
				}
				v.Array[j] = int(uv)
			}
			if err == nil {
				err = BiggerThanTenInt(v.Array[j])
			}
			if err != nil {
				err = errs.NewArrayError(j, err)
				break
			}
		}
	}
	if err == nil {
		err = IntArraySumBiggerThanTen(v.Array)
	}
	if err != nil {
		return i, errs.NewFieldError("Array", err)
	}
	v.ArrayPtr = new([2]int32)
	if buf[i] == 0 {
		i++
		v.ArrayPtr = nil
	} else if buf[i] != 1 {
		i++
		return i, errs.ErrWrongByte
	} else {
		i++
		{
			for j := 0; j < 2; j++ {
				{
					var uv uint32
					{
						if i > len(buf)-1 {
							return i, errs.ErrSmallBuf
						}
						shift := 0
						done := false
						for l, b := range buf[i:] {
							if l == 4 && b > 15 {
								return i, errs.ErrOverflow
							}
							if b < 0x80 {
								uv = uv | uint32(b)<<shift
								done = true
								i += l + 1
								break
							}
							uv = uv | uint32(b&0x7F)<<shift
							shift += 7
						}
						if !done {
							return i, errs.ErrSmallBuf
						}
					}
					if uv&1 == 1 {
						uv = ^(uv >> 1)
					} else {
						uv = uv >> 1
					}
					(*v.ArrayPtr)[j] = int32(uv)
				}
				if err == nil {
					err = BiggerThanTenInt32((*v.ArrayPtr)[j])
				}
				if err != nil {
					err = errs.NewArrayError(j, err)
					break
				}
			}
		}
	}
	if err == nil {
		err = Int32ArrayPtrSumBiggerThanTen(v.ArrayPtr)
	}
	if err != nil {
		return i, errs.NewFieldError("ArrayPtr", err)
	}
	{
		var length int
		{
			var uv uint64
			{
				if i > len(buf)-1 {
					return i, errs.ErrSmallBuf
				}
				shift := 0
				done := false
				for l, b := range buf[i:] {
					if l == 9 && b > 1 {
						return i, errs.ErrOverflow
					}
					if b < 0x80 {
						uv = uv | uint64(b)<<shift
						done = true
						i += l + 1
						break
					}
					uv = uv | uint64(b&0x7F)<<shift
					shift += 7
				}
				if !done {
					return i, errs.ErrSmallBuf
				}
			}
			if uv&1 == 1 {
				uv = ^(uv >> 1)
			} else {
				uv = uv >> 1
			}
			length = int(uv)
		}
		if length < 0 {
			return i, errs.ErrNegativeLength
		}
		if length > 5 {
			err = errs.ErrMaxLengthExceeded
		} else {
			v.Map = make(map[string]int)
			for ; length > 0; length-- {
				var kem string
				var vlm int
				{
					var length int
					{
						var uv uint64
						{
							if i > len(buf)-1 {
								return i, errs.ErrSmallBuf
							}
							shift := 0
							done := false
							for l, b := range buf[i:] {
								if l == 9 && b > 1 {
									return i, errs.ErrOverflow
								}
								if b < 0x80 {
									uv = uv | uint64(b)<<shift
									done = true
									i += l + 1
									break
								}
								uv = uv | uint64(b&0x7F)<<shift
								shift += 7
							}
							if !done {
								return i, errs.ErrSmallBuf
							}
						}
						if uv&1 == 1 {
							uv = ^(uv >> 1)
						} else {
							uv = uv >> 1
						}
						length = int(uv)
					}
					if length < 0 {
						return i, errs.ErrNegativeLength
					}
					if len(buf) < i+length {
						return i, errs.ErrSmallBuf
					}
					kem = string(buf[i : i+length])
					i += length
				}
				if err == nil {
					err = StrIsHello(kem)
				}
				if err != nil {
					err = errs.NewMapKeyError(kem, err)
					break
				}
				{
					var uv uint64
					{
						if i > len(buf)-1 {
							return i, errs.ErrSmallBuf
						}
						shift := 0
						done := false
						for l, b := range buf[i:] {
							if l == 9 && b > 1 {
								return i, errs.ErrOverflow
							}
							if b < 0x80 {
								uv = uv | uint64(b)<<shift
								done = true
								i += l + 1
								break
							}
							uv = uv | uint64(b&0x7F)<<shift
							shift += 7
						}
						if !done {
							return i, errs.ErrSmallBuf
						}
					}
					if uv&1 == 1 {
						uv = ^(uv >> 1)
					} else {
						uv = uv >> 1
					}
					vlm = int(uv)
				}
				if err == nil {
					err = BiggerThanTenInt(vlm)
				}
				if err != nil {
					err = errs.NewMapValueError(kem, vlm, err)
					break
				}
				(v.Map)[kem] = vlm
			}
		}
	}
	if err == nil {
		err = MapSumBiggerThanTen(v.Map)
	}
	if err != nil {
		return i, errs.NewFieldError("Map", err)
	}
	v.MapPtr = new(map[string]int)
	if buf[i] == 0 {
		i++
		v.MapPtr = nil
	} else if buf[i] != 1 {
		i++
		return i, errs.ErrWrongByte
	} else {
		i++
		{
			var length int
			{
				var uv uint64
				{
					if i > len(buf)-1 {
						return i, errs.ErrSmallBuf
					}
					shift := 0
					done := false
					for l, b := range buf[i:] {
						if l == 9 && b > 1 {
							return i, errs.ErrOverflow
						}
						if b < 0x80 {
							uv = uv | uint64(b)<<shift
							done = true
							i += l + 1
							break
						}
						uv = uv | uint64(b&0x7F)<<shift
						shift += 7
					}
					if !done {
						return i, errs.ErrSmallBuf
					}
				}
				if uv&1 == 1 {
					uv = ^(uv >> 1)
				} else {
					uv = uv >> 1
				}
				length = int(uv)
			}
			if length < 0 {
				return i, errs.ErrNegativeLength
			}
			if length > 4 {
				err = errs.ErrMaxLengthExceeded
			} else {
				(*v.MapPtr) = make(map[string]int)
				for ; length > 0; length-- {
					var kem string
					var vlm int
					{
						var length int
						{
							var uv uint64
							{
								if i > len(buf)-1 {
									return i, errs.ErrSmallBuf
								}
								shift := 0
								done := false
								for l, b := range buf[i:] {
									if l == 9 && b > 1 {
										return i, errs.ErrOverflow
									}
									if b < 0x80 {
										uv = uv | uint64(b)<<shift
										done = true
										i += l + 1
										break
									}
									uv = uv | uint64(b&0x7F)<<shift
									shift += 7
								}
								if !done {
									return i, errs.ErrSmallBuf
								}
							}
							if uv&1 == 1 {
								uv = ^(uv >> 1)
							} else {
								uv = uv >> 1
							}
							length = int(uv)
						}
						if length < 0 {
							return i, errs.ErrNegativeLength
						}
						if len(buf) < i+length {
							return i, errs.ErrSmallBuf
						}
						kem = string(buf[i : i+length])
						i += length
					}
					if err == nil {
						err = StrIsHello(kem)
					}
					if err != nil {
						err = errs.NewMapKeyError(kem, err)
						break
					}
					{
						var uv uint64
						{
							if i > len(buf)-1 {
								return i, errs.ErrSmallBuf
							}
							shift := 0
							done := false
							for l, b := range buf[i:] {
								if l == 9 && b > 1 {
									return i, errs.ErrOverflow
								}
								if b < 0x80 {
									uv = uv | uint64(b)<<shift
									done = true
									i += l + 1
									break
								}
								uv = uv | uint64(b&0x7F)<<shift
								shift += 7
							}
							if !done {
								return i, errs.ErrSmallBuf
							}
						}
						if uv&1 == 1 {
							uv = ^(uv >> 1)
						} else {
							uv = uv >> 1
						}
						vlm = int(uv)
					}
					if err == nil {
						err = BiggerThanTenInt(vlm)
					}
					if err != nil {
						err = errs.NewMapValueError(kem, vlm, err)
						break
					}
					(*v.MapPtr)[kem] = vlm
				}
			}
		}
	}
	if err == nil {
		err = MapPtrSumBiggerThanTen(v.MapPtr)
	}
	if err != nil {
		return i, errs.NewFieldError("MapPtr", err)
	}
	{
		var sv SimpleStructType
		si := 0
		si, err = sv.Unmarshal(buf[i:])
		if err == nil {
			v.Struct = sv
			i += si
		}
	}
	if err == nil {
		err = ValidSimpleStructType(v.Struct)
	}
	if err != nil {
		return i, errs.NewFieldError("Struct", err)
	}
	v.StructPtr = new(SimpleStructType)
	if buf[i] == 0 {
		i++
		v.StructPtr = nil
	} else if buf[i] != 1 {
		i++
		return i, errs.ErrWrongByte
	} else {
		i++
		{
			var sv SimpleStructType
			si := 0
			si, err = sv.Unmarshal(buf[i:])
			if err == nil {
				(*v.StructPtr) = sv
				i += si
			}
		}
	}
	if err == nil {
		err = ValidSimpleStructPtrType(v.StructPtr)
	}
	if err != nil {
		return i, errs.NewFieldError("StructPtr", err)
	}
	return i, err
}

// Size returns the size of the MUS-encoded v.
func (v ValidStructType) Size() int {
	size := 0
	{
		for v.Uint64 >= 0x80 {
			v.Uint64 >>= 7
			size++
		}
		size++
	}
	{
		_ = v.Int8
		size++
	}
	{
		length := len(v.String)
		{
			uv := uint64(length<<1) ^ uint64(length>>63)
			{
				for uv >= 0x80 {
					uv >>= 7
					size++
				}
				size++
			}
		}
		size += len(v.String)
	}
	size++
	if v.StringPtr != nil {
		{
			length := len((*v.StringPtr))
			{
				uv := uint64(length<<1) ^ uint64(length>>63)
				{
					for uv >= 0x80 {
						uv >>= 7
						size++
					}
					size++
				}
			}
			size += len((*v.StringPtr))
		}
	}
	{
		_ = v.Byte
		size++
	}
	{
		_ = v.Bool
		size++
	}
	{
		length := len(v.Slice)
		{
			uv := uint64(length<<1) ^ uint64(length>>63)
			{
				for uv >= 0x80 {
					uv >>= 7
					size++
				}
				size++
			}
		}
		for _, el := range v.Slice {
			{
				for el >= 0x80 {
					el >>= 7
					size++
				}
				size++
			}
		}
	}
	size++
	if v.SlicePtr != nil {
		{
			length := len((*v.SlicePtr))
			{
				uv := uint64(length<<1) ^ uint64(length>>63)
				{
					for uv >= 0x80 {
						uv >>= 7
						size++
					}
					size++
				}
			}
			for _, el := range *v.SlicePtr {
				{
					for el >= 0x80 {
						el >>= 7
						size++
					}
					size++
				}
			}
		}
	}
	{
		for _, item := range v.Array {
			{
				uv := uint64(item<<1) ^ uint64(item>>63)
				{
					for uv >= 0x80 {
						uv >>= 7
						size++
					}
					size++
				}
			}
		}
	}
	size++
	if v.ArrayPtr != nil {
		{
			for _, item := range *v.ArrayPtr {
				{
					uv := uint32(item<<1) ^ uint32(item>>31)
					{
						for uv >= 0x80 {
							uv >>= 7
							size++
						}
						size++
					}
				}
			}
		}
	}
	{
		length := len(v.Map)
		{
			uv := uint64(length<<1) ^ uint64(length>>63)
			{
				for uv >= 0x80 {
					uv >>= 7
					size++
				}
				size++
			}
		}
		for ke, vl := range v.Map {
			{
				length := len(ke)
				{
					uv := uint64(length<<1) ^ uint64(length>>63)
					{
						for uv >= 0x80 {
							uv >>= 7
							size++
						}
						size++
					}
				}
				size += len(ke)
			}
			{
				uv := uint64(vl<<1) ^ uint64(vl>>63)
				{
					for uv >= 0x80 {
						uv >>= 7
						size++
					}
					size++
				}
			}
		}
	}
	size++
	if v.MapPtr != nil {
		{
			length := len((*v.MapPtr))
			{
				uv := uint64(length<<1) ^ uint64(length>>63)
				{
					for uv >= 0x80 {
						uv >>= 7
						size++
					}
					size++
				}
			}
			for ke, vl := range *v.MapPtr {
				{
					length := len(ke)
					{
						uv := uint64(length<<1) ^ uint64(length>>63)
						{
							for uv >= 0x80 {
								uv >>= 7
								size++
							}
							size++
						}
					}
					size += len(ke)
				}
				{
					uv := uint64(vl<<1) ^ uint64(vl>>63)
					{
						for uv >= 0x80 {
							uv >>= 7
							size++
						}
						size++
					}
				}
			}
		}
	}
	{
		ss := v.Struct.Size()
		size += ss
	}
	size++
	if v.StructPtr != nil {
		{
			ss := (*v.StructPtr).Size()
			size += ss
		}
	}
	return size
}
